#!/usr/bin/env node
// Static site build: data/*.json + src/ templates -> HTML pages at the repository root.
// No dependencies; run with `node tools/build.mjs`. The GitHub Pages workflow runs it on every push,
// so edits made in admin.html (which commit data/*.json) go live without a local build.
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { layout } from '../src/partials.mjs';
import { hashString } from '../src/lib/util.mjs';
import { homePage } from '../src/pages/home.mjs';
import { listingPage } from '../src/pages/properties.mjs';
import { propertyPage } from '../src/pages/property.mjs';
import { goldenVisaPage } from '../src/pages/golden-visa.mjs';
import { whyPage } from '../src/pages/why.mjs';
import { testimonialsPage } from '../src/pages/testimonials.mjs';
import { contactPage } from '../src/pages/contact.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const readJSON = async f => JSON.parse(await fs.readFile(path.join(root, f), 'utf8'));
const exists = f => fs.access(path.join(root, f)).then(() => true, () => false);

// Stylesheet sources live in src/css (one file per area, applied in name order); browsers get one file.
async function buildCSS() {
  const dir = path.join(root, 'src/css');
  const files = (await fs.readdir(dir)).filter(f => f.endsWith('.css')).sort();
  let css = '/* Generated by tools/build.mjs from src/css. Edit the sources, not this file. */\n';
  for (const f of files) css += `\n/* ---- ${f} ---- */\n` + await fs.readFile(path.join(dir, f), 'utf8');
  await fs.mkdir(path.join(root, 'assets/css'), { recursive: true });
  await fs.writeFile(path.join(root, 'assets/css/site.css'), css);
}

async function assetVersion() {
  const files = ['assets/css/site.css', ...(await fs.readdir(path.join(root, 'assets/js'))).map(f => 'assets/js/' + f)];
  let all = '';
  for (const f of files) all += await fs.readFile(path.join(root, f), 'utf8').catch(() => '');
  return hashString(all);
}

async function main() {
  const site = await readJSON('data/site.json');
  const tax = await readJSON('data/taxonomy.json');
  const { properties } = await readJSON('data/properties.json');
  // Client stories appear only with the client's written consent (ticked in the admin) and a quote and name.
  const testimonials = ((await exists('data/testimonials.json')) ? (await readJSON('data/testimonials.json')).testimonials || [] : [])
    .filter(t => t.consent !== false && String(t.quote || '').trim() && String(t.name || '').trim());
  const faq = await readJSON('data/faq.json');
  await buildCSS();
  const ctx = { site, tax, properties, testimonials, faq, v: await assetVersion() };

  const pages = [
    homePage(ctx),
    listingPage(ctx),
    ...properties.map(p => propertyPage(ctx, p)),
    goldenVisaPage(ctx),
    whyPage(ctx),
    testimonialsPage(ctx),
    contactPage(ctx)
  ];

  for (const page of pages) {
    await fs.writeFile(path.join(root, page.path), layout(ctx, page));
  }

  // Remove detail pages of listings that were deleted in the admin.
  const keep = new Set(pages.map(p => p.path));
  for (const f of await fs.readdir(root)) {
    if (/^property-.+\.html$/.test(f) && !keep.has(f)) await fs.unlink(path.join(root, f));
  }

  const base = site.indexable ? site.siteUrl.replace(/\/$/, '') + '/' : site.previewUrl;
  const urls = pages.map(p => `  <url><loc>${base}${p.path === 'index.html' ? '' : p.path}</loc></url>`).join('\n');
  await fs.writeFile(path.join(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`);
  await fs.writeFile(path.join(root, 'robots.txt'), site.indexable
    ? `User-agent: *\nAllow: /\nDisallow: /admin.html\n\nSitemap: ${base}sitemap.xml\n`
    : `# Preview build: the redesign concept is not meant to be indexed.\nUser-agent: *\nDisallow: /\n`);

  console.log(`built ${pages.length} pages (assets v=${ctx.v})`);
}

main().catch(e => { console.error(e); process.exit(1); });
